# Generated by Django 4.2 on 2023-05-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_postalcode_shippingaddress_postal_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='qty',
        ),
    ]
