# Generated by Django 4.2 on 2023-05-10 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_quantity_orderitem_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='created_time',
            new_name='createdTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='delivery_time',
            new_name='deliveryTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_delivered',
            new_name='isDelivered',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='is_paid',
            new_name='isPaid',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_method',
            new_name='paymentMethod',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='payment_time',
            new_name='paymentTime',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='shipping_price',
            new_name='shippingPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='tax_price',
            new_name='taxPrice',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='total_price',
            new_name='totalPrice',
        ),
    ]
