# Generated by Django 4.2 on 2023-05-10 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_created_time_order_createdtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='postal_code',
            new_name='postalCode',
        ),
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='shipping_price',
            new_name='shippingPrice',
        ),
    ]
