# Generated by Django 4.2 on 2023-05-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_rename_postal_code_shippingaddress_postalcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='shippingPrice',
        ),
    ]
